name: learn-github-actions
on: [push]
jobs:
  check-jest-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [6, 8, 10]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-versoin: ${{ matrix.node }}
      - run: npm install -g jest
      - run: jest -v

jobs:
  job-one:
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > job-one-output.log
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: job-one-output-log-file
          path: job-one-output.log

jobs:
  job-two:
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: job-one-output-log-file