name: save-output-log-file
on: [push]

jobs:
  job-one:
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > job-one-output.log
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: job-one-output-log-file
          path: job-one-output.log
